language: node_js
cache: yarn
notifications:
  email: false
node_js:
    - node
install:
  - yarn install --ignore-engines
scripts:
  - yarn storybook-build
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
branches:
  only:
    - master
